Add ParagraphPreprocess event
pdenooijer/hook_event_dispatcher pull request #10
Opened 2017-10-13 09:41 UTC by guiajlopes

2017-10-13 13:22 UTC, pdenooijer commented on src/Event/Preprocess/Variables/ParagraphEventVariables.php
> +}
Please add a line-break.

2017-10-13 13:23 UTC, pdenooijer commented
Thank you for your contribution!
I'll try to merge it this weekend 🙂.

2017-10-13 13:42 UTC, guiajlopes commented on src/Event/Preprocess/Variables/ParagraphEventVariables.php
> +}
updated

2017-10-13 20:48 UTC, pdenooijer requested changes
Please extend Preproces unit tests with your new class 🙂

2017-10-16 08:16 UTC, pdenooijer commented
Please rebase on the 8.x-1.x branch 🙂

2017-10-16 12:21 UTC, pdenooijer approved these changes

2017-10-16 12:21 UTC, merged