Added FieldWidgetThirdPartySettingsFormEvent.
pdenooijer/hook_event_dispatcher pull request #114
Opened 2020-01-31 10:02 UTC by Ambient-Impact

See #103. Will merge duplicate code in follow-up PR.

2020-01-31 10:20 UTC, pdenooijer requested changes

2020-01-31 10:20 UTC, pdenooijer commented on modules/field_event_dispatcher/field_event_dispatcher.services.yml
> +field_event_dispatcher.form_entity_form_display_edit_alter_event_subscriber:
Please add a new line between service defs.
Add missing 2 spaces before this.
Update the naming with the above naming as an example.

2020-01-31 10:20 UTC, pdenooijer commented on modules/field_event_dispatcher/field_event_dispatcher.services.yml
> +    arguments: []
This is not used so please remove it.

2020-01-31 10:20 UTC, pdenooijer commented on modules/field_event_dispatcher/src/EventSubscriber/Form/FormEntityFormDisplayEditAlterEventSubscriber.php
> +      $fieldSettings = &$form['fields'][$fieldName]['plugin']['settings_edit_form'];
Please use the third part settings instead so you don't need the key anymore 🙂:
`$thirdPartySettings = &$form['fields'][$fieldName]['plugin']['settings_edit_form']['third_party_settings'];`

2020-01-31 22:36 UTC, Ambient-Impact commented
That's what I get for opening a PR right before I go to bed and not thoroughly checking the rebase beforehand. 🤓

2020-02-02 18:01 UTC, pdenooijer approved these changes

2020-02-02 18:21 UTC, merged