Add FieldWidgetSettingsSummaryAlterEvent
pdenooijer/hook_event_dispatcher pull request #118
Opened 2020-02-04 01:18 UTC by Ambient-Impact

See #103. Thought I'd open this at the same time as #117 so I can get both moving since they're similar, but can rebase once one or the other is merged.

2020-02-04 08:07 UTC, pdenooijer commented
Can you rebase this and reuse abstract the event as they are pretty much the same 🙂?

2020-02-04 08:07 UTC, pdenooijer commented on modules/field_event_dispatcher/tests/src/Unit/Field/FieldWidgetSettingsSummaryAlterEventTest.php
> +  public function testContext() {
You can merge this into the previous test as it does not test a different use case.

2020-02-05 13:38 UTC, Ambient-Impact commented
Sure, I can combine the duplicate stuff into abstract classes. At the time, it seemed like they were fairly small classes to begin with, but in hindsight combining still makes more sense.

2020-02-06 18:30 UTC, pdenooijer requested changes
Dots on the i, keep up the good work 🙂 !

2020-02-06 18:30 UTC, pdenooijer commented on modules/field_event_dispatcher/src/Event/Field/AbstractFieldSettingsSummaryFormEvent.php
> +  protected $summary;
No need for this to be protected, it can safely be private as there is no real dependency for the child classes on this.

2020-02-06 18:30 UTC, pdenooijer commented on modules/field_event_dispatcher/tests/src/Unit/Field/AbstractFieldSettingsSummaryAlterEventTestCase.php
> +  protected $manager;
This can be private as it is not used in the child classes, just the abstract methods are implemented.

2020-02-06 18:30 UTC, pdenooijer commented
Two commits is fine indeed. Pretty sure I only have comments on the last commit anyway.

2020-02-07 12:55 UTC, Ambient-Impact commented
Thanks. I guess I'm getting pretty good at this. 😄 

[![A cartoon corgi dancing](https://media.giphy.com/media/l0Exwsr9EkdDCyoF2/source.gif)](https://giphy.com/gifs/corgie-dance-flipnote-animation-l0Exwsr9EkdDCyoF2)

2020-02-08 16:46 UTC, pdenooijer approved these changes
And merge!

2020-02-08 16:46 UTC, pdenooijer commented on modules/field_event_dispatcher/tests/src/Unit/Field/AbstractFieldSettingsSummaryAlterEventTestCase.php
> +  abstract protected static function getProceduralHookName(): string;
Nitpick: there is no real need for this to be static.

2020-02-08 16:46 UTC, pdenooijer commented on modules/field_event_dispatcher/tests/src/Unit/Field/AbstractFieldSettingsSummaryAlterEventTestCase.php
> +  abstract protected static function getEventName(): string;
Same 🙂

2020-02-08 16:47 UTC, merged

2020-02-08 16:54 UTC, Ambient-Impact commented
I actually force pushed the removal of the ```static``` stuff, if you want those changes in.

2020-02-08 17:19 UTC, pdenooijer commented
Ah yeah that could work as well, I'll remove the current merge. Can you make a new PR 🙂 ?

2020-02-08 17:30 UTC, pdenooijer commented
I can do it as well I see 😁