Add EntityBaseFieldInfoAlterEvent
pdenooijer/hook_event_dispatcher pull request #38
Opened 2018-08-15 07:17 UTC by rogierbom1

Added event to replace hook_entity_base_field_info_alter()

2018-08-15 09:25 UTC, pdenooijer requested changes
First of all, thanks for your PR! To merge this, please fix the PHPCS errors and squash your commits to one commit 🙂.

2018-08-15 09:25 UTC, pdenooijer commented on tests/src/Unit/EntityType/EntityBaseFieldInfoAlterEventTest.php
> +  public function testEntityBaseFieldInfoEvent() {
This test misses the real life usage of this event, please add an extra field to the fields after the event is fired. You can look up how I do this with the HookEventDispatcherManagerSpy in other tests. You could have a look at the `ViewEventTest` for instance.

2018-08-15 15:09 UTC, rogierbom1 commented
Done.

2018-08-15 19:32 UTC, pdenooijer requested changes

2018-08-15 19:32 UTC, pdenooijer commented on hook_event_dispatcher.module
> +  return $event->getFields();
Ah sorry mist this in the first round. My last nitpick, please remove this line as the by reference fields is used and not the returned array.

2018-08-16 07:26 UTC, rogierbom1 commented
- Removed returning of the fields
- Expanded Unittest with check for getEntityType() for full coverage

2018-08-16 07:58 UTC, pdenooijer approved these changes

2018-08-16 07:58 UTC, merged

2018-08-16 07:59 UTC, pdenooijer commented
Thnx 👍

2018-08-16 07:59 UTC, pdenooijer commented
Dev version on drupal.org has your changes 👍