Add support missing views hooks
pdenooijer/hook_event_dispatcher pull request #74
Opened 2019-07-05 23:43 UTC by Etroid

Creates events for:
- `hook_views_pre_view`
- `hook_views_query_substitutions`
- `hook_views_pre_render`
- `hook_views_post_render`

2019-07-09 08:27 UTC, pdenooijer requested changes
Thanks for the PR!

2019-07-09 08:27 UTC, pdenooijer commented on hook_event_dispatcher.module
> +use Drupal\hook_event_dispatcher\Event\Views\ViewsPreViewEvent as ViewsPreViewEventAlias;
I guess we don't need this twice 😉

2019-07-09 08:27 UTC, pdenooijer commented on hook_event_dispatcher.module
> +use Drupal\hook_event_dispatcher\Event\Views\ViewsQuerySubstitutionsEvent as ViewsQuerySubstitutionsEventAlias;
Idem

2019-07-09 08:27 UTC, pdenooijer commented on src/Event/Views/ViewsPostRenderEvent.php
> +  protected $output;
Does this needs to be protected or will private suffice?

2019-07-09 08:27 UTC, pdenooijer commented on src/Event/Views/ViewsPreViewEvent.php
> +  protected $args;
Does this need to be protected?

2019-07-09 08:27 UTC, pdenooijer commented on src/Event/Views/ViewsQuerySubstitutionsEvent.php
> +  public function getSubstitutions() {
Isn't this better to get by reference? So you can add to the current array instead of overwriting the array with set every time?

2019-07-09 08:27 UTC, pdenooijer commented on src/Event/Views/ViewsQuerySubstitutionsEvent.php
> +  private $substitutions;
Please set this to `[]` as sensible default.

2019-07-09 08:27 UTC, pdenooijer commented on src/Event/Views/ViewsPreViewEvent.php
> +  public function &getArgs() {
I think this should just be called `getArguments`, no need to shorten this. Same for the hook and the field in this class.

2019-07-09 16:59 UTC, Etroid commented
@pdenooijer thanks for the feedback. I've addressed it in the latest commit

2019-07-31 11:28 UTC, pdenooijer approved these changes

2019-07-31 11:29 UTC, merged

2019-07-31 11:29 UTC, pdenooijer commented
Thanks @Etroid !